# Generated by Django 5.1.4 on 2024-12-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubstringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_string', models.CharField(max_length=255)),
                ('length_of_longest_substring', models.IntegerField()),
            ],
        ),
    ]
